[problem]
name = "OoC_Grid_Problem"
neq = 4
problem_type = "ooc"

[time_parameters]
T = 3600.0
dt = 16.0

[discretization]
h = 15.0
tau = [ 0.5, 0.5, 0.5, 0.5,]

[initial_conditions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[force_functions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[domain_initial_conditions]
domain_0_v = "gaussian"
domain_3_u = "gaussian"

[domain_force_functions]

[boundary_conditions]

[physical_parameters.viscosity]
nu = 30.0
mu = 30.0
epsilon = 30.0
sigma = 56.0

[physical_parameters.reaction]
a = 0.0005
c = 0.0005

[physical_parameters.coupling]
b = 0.1
d = 0.1

[physical_parameters.chemotaxis]
type = "receptor_saturation"
k1 = 3.9e-9
k2 = 4.9999999999999996e-6

[physical_parameters.tumor_suppression]
m1 = 1.9000000000000002e-11
m2 = 0.0001
