[problem]
name = "OoC_Grid_Problem"
neq = 4
problem_type = "ooc"

[time_parameters]
T = 2.0
dt = 0.005

[discretization]
n_elements = 80
tau = [ 0.5, 0.5, 0.5, 0.5,]

[initial_conditions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[force_functions]
u = "zeros"
omega = "zeros"
v = "zeros"
phi = "zeros"

[domain_initial_conditions]
domain_0_v = "constant"
domain_5_u = "constant"

[domain_force_functions]

[physical_parameters.viscosity]
nu = 141.9539783058973
mu = 934.079909897664
epsilon = 886.491343968811
sigma = 194.98238097930783

[physical_parameters.reaction]
a = 0.0001
c = 0.1

[physical_parameters.coupling]
b = 0.0001
d = 0.1

[physical_parameters.chemotaxis]
type = "receptor_saturation"
k1 = 3.9e-9
k2 = 5e-6

[physical_parameters.tumor_suppression]
m1 = 1.0
m2 = 1.0
